### PR TITLE
Add Starred-Question Navigation to Outline

### PR DESCRIPTION
**Pull request by dnsge**
This pull request expands the functionality of marking questions with stars while taking the exam.

When a user marks a question with a star, the question will now become visible in the left sidebar outline underneath the question's corresponding section. This allows users to easily see how many questions they have starred (likely questions that they want to double-check or that they initially skipped) and to easily navigate to the question with a click.

Here is a video of the feature in action:

https://user-images.githubusercontent.com/24928223/144729554-c55374a7-f443-4ba8-9b1a-3b3ae249917d.mov

In addition to adding the starred question functionality, the left sidebar has been updated to use flexbox and will play nicer with lots of sections (and now marked questions) by introducing a scrollbar when there is too much content. The scrollbar is styled to be always visible as long as the content is scrollable so users won't unknowingly miss any sections or marked questions. 

(My idea for this implementation came from Canvas quizzes and my desire to see which questions I had starred during the last exam)

### CODE REVIEW

**Comment by jamesjuett** [comment]
Thanks so much for this PR! It's a big improvement to the usability of the stars (and something I'd meant to implement eventually) and I expect would make it a lot easier to track which questions someone marked if they're using the stars to know what to go back to.

I'll see if I can get this reviewed and merged in the next few days. (If that happens, I'll also bump the live practice final that's out for 280 right now so that it has the new feature.)

**Comment by jamesjuett** [comment]
Thought you deserved an update - unfortunately, I'm not going to end up with enough time to properly review this before the 280 final exam on Tuesday. I've taken a look through the code and generally everything looks fine, but we just passed our last internal test of the exam with staff, so there won't be a chance to sanity check that nothing breaks.

I'll definitely get to this eventually, and future students will benefit from your contribution!

**Comment by dnsge** [comment]
That's perfectly fine! I understand how important it is for any changes to be thoroughly tested -- I wouldn't want my change responsible for breaking anyone's final exam. I can only imagine how much of a disaster that would be for everyone involved.

**Comment by jamesjuett** [comment]
I finally had time to review this. After a few minor changes (primarily for style consistency), everything looks good! I'm merging and we'll get this out with our EECS 280 practice final exam for the W22 term.

Thanks again for your contribution!

**Pull request merged**
